services:
  Pixxio\PixxioExtension\Command\SyncCommand:
    tags:
      - name: 'console.command'
        command: 'pixxio:sync'
        description: 'Sync alternative text, description and title with your pixx.io system'
        # not required, defaults to false
        hidden: false